-- MySQL Script generated by MySQL Workbench
-- lun 31 ene 2022 14:27:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Race`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Race` (
  `idRace` INT NOT NULL AUTO_INCREMENT,
  `nameRace` VARCHAR(45) NULL,
  PRIMARY KEY (`idRace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Character` (
  `idCharacter` INT NOT NULL AUTO_INCREMENT,
  `nameCharacter` VARCHAR(45) NULL,
  `length` VARCHAR(45) NULL,
  `karma` INT NULL,
  `Race_idRace` INT NOT NULL,
  PRIMARY KEY (`idCharacter`),
  INDEX `fk_Character_Race_idx` (`Race_idRace` ASC) VISIBLE,
  CONSTRAINT `fk_Character_Race`
    FOREIGN KEY (`Race_idRace`)
    REFERENCES `mydb`.`Race` (`idRace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Place` (
  `idplace` INT NOT NULL AUTO_INCREMENT,
  `namePlace` VARCHAR(45) NULL,
  PRIMARY KEY (`idplace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Affiliation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Affiliation` (
  `idaffiliation` INT NOT NULL AUTO_INCREMENT,
  `nameAffiliation` VARCHAR(45) NULL,
  PRIMARY KEY (`idaffiliation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ocupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ocupation` (
  `idOcupation` INT NOT NULL AUTO_INCREMENT,
  `nameOCupation` VARCHAR(45) NULL,
  PRIMARY KEY (`idOcupation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Place_has_Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Place_has_Character` (
  `Place_idplace` INT NOT NULL,
  `Character_idCharacter` INT NOT NULL,
  `currentPlace` TINYINT NULL,
  PRIMARY KEY (`Place_idplace`, `Character_idCharacter`),
  INDEX `fk_Place_has_Character_Character1_idx` (`Character_idCharacter` ASC) VISIBLE,
  INDEX `fk_Place_has_Character_Place1_idx` (`Place_idplace` ASC) VISIBLE,
  CONSTRAINT `fk_Place_has_Character_Place1`
    FOREIGN KEY (`Place_idplace`)
    REFERENCES `mydb`.`Place` (`idplace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Place_has_Character_Character1`
    FOREIGN KEY (`Character_idCharacter`)
    REFERENCES `mydb`.`Character` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Affiliation_has_Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Affiliation_has_Character` (
  `Affiliation_idaffiliation` INT NOT NULL,
  `Character_idCharacter` INT NOT NULL,
  PRIMARY KEY (`Affiliation_idaffiliation`, `Character_idCharacter`),
  INDEX `fk_Affiliation_has_Character_Character1_idx` (`Character_idCharacter` ASC) VISIBLE,
  INDEX `fk_Affiliation_has_Character_Affiliation1_idx` (`Affiliation_idaffiliation` ASC) VISIBLE,
  CONSTRAINT `fk_Affiliation_has_Character_Affiliation1`
    FOREIGN KEY (`Affiliation_idaffiliation`)
    REFERENCES `mydb`.`Affiliation` (`idaffiliation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Affiliation_has_Character_Character1`
    FOREIGN KEY (`Character_idCharacter`)
    REFERENCES `mydb`.`Character` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Character_has_Ocupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Character_has_Ocupation` (
  `Character_idCharacter` INT NOT NULL,
  `Ocupation_idOcupation` INT NOT NULL,
  PRIMARY KEY (`Character_idCharacter`, `Ocupation_idOcupation`),
  INDEX `fk_Character_has_Ocupation_Ocupation1_idx` (`Ocupation_idOcupation` ASC) VISIBLE,
  INDEX `fk_Character_has_Ocupation_Character1_idx` (`Character_idCharacter` ASC) VISIBLE,
  CONSTRAINT `fk_Character_has_Ocupation_Character1`
    FOREIGN KEY (`Character_idCharacter`)
    REFERENCES `mydb`.`Character` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Character_has_Ocupation_Ocupation1`
    FOREIGN KEY (`Ocupation_idOcupation`)
    REFERENCES `mydb`.`Ocupation` (`idOcupation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
